# Generated by Django 2.0.3 on 2018-03-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64)),
                ('house_number', models.CharField(max_length=16)),
                ('flat_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('patronymic', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_phone', models.CharField(max_length=32)),
                ('work_phone', models.CharField(max_length=32)),
                ('home_phone', models.CharField(max_length=32)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=16)),
                ('biography', models.CharField(max_length=10000)),
                ('interests', models.CharField(max_length=1000)),
                ('photo', models.URLField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models_test.Address')),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
