# Generated by Django 2.0.3 on 2018-03-23 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_test', '0002_auto_20180323_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='models_test.Address'),
        ),
    ]
